[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["npm install --omit=dev || npm install"]

[phases.build]
cmds = ["npx prisma generate", "npx prisma migrate deploy --schema=dfp-neo-platform/prisma/schema.prisma"]

[start]
cmd = "node server.js"