import { NextRequest, NextResponse } from 'next/server';
import * as crypto from 'crypto';

/**
 * Validate an authentication token generated by the website
 * This allows single sign-on from the website to the V2 app
 * 
 * GET /api/auth/validate-token?authToken=xxx&userId=xxx
 * 
 * Returns user data if token is valid
 */
export async function GET(request: NextRequest) {
  try {
    const searchParams = request.nextUrl.searchParams;
    const authToken = searchParams.get('authToken');
    const userId = searchParams.get('userId');

    if (!authToken || !userId) {
      return NextResponse.json(
        { error: 'Bad request', message: 'Missing authToken or userId' },
        { 
          status: 400,
          headers: {
            'Access-Control-Allow-Origin': '*',
            'Access-Control-Allow-Methods': 'GET, OPTIONS',
            'Access-Control-Allow-Headers': 'Content-Type',
          }
        }
      );
    }

    // Split token and signature
    const lastDotIndex = authToken.lastIndexOf('.');
    if (lastDotIndex === -1) {
      return NextResponse.json(
        { error: 'Invalid token', message: 'Token format is invalid' },
        { 
          status: 401,
          headers: { 'Access-Control-Allow-Origin': '*' }
        }
      );
    }

    const token = authToken.substring(0, lastDotIndex);
    const signature = authToken.substring(lastDotIndex + 1);

    if (!token || !signature) {
      return NextResponse.json(
        { error: 'Invalid token', message: 'Token format is invalid' },
        { 
          status: 401,
          headers: { 'Access-Control-Allow-Origin': '*' }
        }
      );
    }

    // Verify signature
    const secret = process.env.NEXTAUTH_SECRET || 'your-secret-key-change-this-in-production';
    const expectedSignature = crypto
      .createHmac('sha256', secret)
      .update(token)
      .digest('hex');

    if (signature !== expectedSignature) {
      return NextResponse.json(
        { error: 'Invalid token', message: 'Token signature is invalid' },
        { 
          status: 401,
          headers: { 'Access-Control-Allow-Origin': '*' }
        }
      );
    }

    // Decode token
    let tokenData;
    try {
      const decoded = Buffer.from(token, 'base64').toString('utf-8');
      tokenData = JSON.parse(decoded);
    } catch (error) {
      return NextResponse.json(
        { error: 'Invalid token', message: 'Failed to decode token' },
        { 
          status: 401,
          headers: { 'Access-Control-Allow-Origin': '*' }
        }
      );
    }

    // Check if token has expired
    if (Date.now() > tokenData.expiresAt) {
      return NextResponse.json(
        { error: 'Expired token', message: 'Token has expired' },
        { 
          status: 401,
          headers: { 'Access-Control-Allow-Origin': '*' }
        }
      );
    }

    // Verify userId matches
    if (tokenData.userId !== userId) {
      return NextResponse.json(
        { error: 'Invalid token', message: 'User ID does not match' },
        { 
          status: 401,
          headers: { 'Access-Control-Allow-Origin': '*' }
        }
      );
    }

    // Return user data with CORS headers
    return NextResponse.json(
      {
        valid: true,
        user: {
          userId: tokenData.userId,
          username: tokenData.username,
          firstName: tokenData.firstName,
          lastName: tokenData.lastName,
          email: tokenData.email,
          role: tokenData.role,
          isActive: tokenData.isActive
        }
      },
      {
        headers: {
          'Access-Control-Allow-Origin': '*',
          'Access-Control-Allow-Methods': 'GET, OPTIONS',
          'Access-Control-Allow-Headers': 'Content-Type',
        }
      }
    );
  } catch (error) {
    console.error('Error validating token:', error);
    return NextResponse.json(
      { error: 'Internal server error', message: 'Failed to validate token' },
      { 
        status: 500,
        headers: { 'Access-Control-Allow-Origin': '*' }
      }
    );
  }
}

// Handle CORS preflight requests
export async function OPTIONS() {
  return NextResponse.json(
    {},
    {
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'GET, OPTIONS',
        'Access-Control-Allow-Headers': 'Content-Type',
      }
    }
  );
}